language: python

python:
  - 3.8
 
 before_install:
  - pip install xlsxwriter
  - pip install tkinter
  - pip install csv
  - pip install win32com.client
 
 script: python generator.py ./ tables 5 10 long vertical
